
function out = objFunction(gam,I,mask,dz,g,D,eta)

  m = numel(I);
  ut = triu( ones(m-1,m-1) );

  
  out = 0.5 * sum( ...
           ... % Integrate from z to D
           mask(1:m-1) .*(...
            ( 1/2 * I(1:m-1) .* gam(1:m-1) ./ dz ...
             - 1/2 * I(m) * gam(m) ./ dz ...
             + 1/2 * ut * ( ...
                 I(1:m-1) ./ dz .* gam(1:m-1) .* log( g(2:m)./g(1:m-1) ) ...
             ) ...
           - ut * I(1:m-1) ...
           ).^2 ...
         ) ...
      ) ...
      + eta * sum( mask .* abs( D * gam ) );
end


