
function out = objFunction(gam,I,dz,g,D,eta)
  m = numel(I);
  ut = triu( ones(m-1,m-1) );
  out = 0.5 * sum( ...
           ... % Integrate from z to D
           ( 1/2 * I(1:m-1) .* gam(1:m-1) ./ dz ...
           - 1/2 * I(m) * gam(m) / dz ...
           + 1/2 * ut * ( ...
               I(1:m-1) ./ dz .* gam(1:m-1) .* log( g(2:m)./g(1:m-1) ) ...
             ) ...
           - ut * I(1:m-1) ...
           ).^2 ...
      ) ...
      + eta * norm( D * gam, 1 );
end

